# Generated by Django 4.1.1 on 2022-11-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-09-09'),
            preserve_default=False,
        ),
    ]
